### ISSUE TITLE
[Bug] Server crashes when trying to accessing /auth/settings/ 

### ISSUE THREAD

**Issue by ZerGo0** [rubenmoor/learn-palantype#48]
## Describe the problem:

The server crashes when you go to `/auth/settings/`

### Steps to reproduce:

  1. Login
  2. Open the settings menu in the top left
  3. Click `Go to settings`
  
### Observed Results:

  * What happened?
  The site never opened and reloading returned 502 nginx error.

  * What did you expect to happen?
  The settings page should appear

### Relevant code exceptions or logs

Nothing

**Comment by rubenmoor** [comment]
thanks for reporting. I will look into this

**Comment by rubenmoor** [comment]
Fixed
